@startuml
left to right direction
actor Aplicación
rectangle Calculadora{
    usecase Sumar
    usecase Dividir
    usecase Restar
    usecase Multiplicar
    usecase Consultal el histórico de operaciones
    usecase "Sumar Enteros" as se
    usecase "Sumar Reales" as sr

    Aplicación -- Sumar
    Aplicación -- Dividir
    Aplicación -- Restar
    Aplicación -- Multiplicar
    Aplicación -- Consultal el histórico de operaciones

    Sumar <|-- se
    Sumar <|-- sr
}
@enduml
